Repository DreamVault-2024/dreamvalut-frontend, pull requests merged in 2024-04, with the labels that each got.

#40 [feat] 장르페이지 기능, 마이페이지 - 장르 변경 기능 구현
  package.json
  src/app/GenrePage/page.tsx
  src/app/LogInPage/page.tsx
  src/app/MymusicAI/page.tsx
  src/app/MymusicAI/practice.tsx
  src/app/api/genre.ts
  src/app/auth/_app.tsx
  src/app/auth/nextauth.ts
  src/app/components/NavBar/NavigationBar.tsx
  src/app/globals.css
  src/app/instumentation.ts
  src/app/main/page.tsx
  src/app/mocks/browser.ts
  src/app/mocks/handlers.ts
  src/app/mocks/server.ts
  src/app/mypage/page.tsx
  src/app/page.tsx
  src/app/types/genre.ts
  tsconfig.json
  yarn.lock
Labels: 🚀 Feat, 🎨 Design

#42 [feat] 인기 차트 API 연동 및 Mocking Data 적용
  package.json
  src/app/layout.tsx
  src/app/main/page.tsx
  src/app/styles/SlideStyles.ts
  src/app/styles/globals.css
  src/mocks/MSWcomponent.tsx
  src/mocks/browser.ts
  src/mocks/handlers/chartHandlers.ts
  src/mocks/handlers/handlers.ts
  src/mocks/index.ts
  src/mocks/server.ts
  yarn.lock
Labels: 🚀 Feat

#44 [chore] react-query 설정
  package.json
  src/api/genre.ts
  src/api/music.ts
  src/app/components/Musicbar/Musicbar.tsx
  src/app/components/QueryProvider/QueryProvider.tsx
  src/app/layout.tsx
  src/app/mypage/page.tsx
  src/mocks/MSWComponent.tsx
  src/types/genre.ts
  src/types/music.ts
  yarn.lock
Labels: 🧭 Chore, 🚀 Feat

#46 [feat] 검색기능구현
  src/app/components/NavBar/NavigationBar.tsx
  src/app/search/[keyward]/page.tsx
  src/app/search/page.tsx
  src/app/styles/globals.css
  src/mocks/browser.ts
  src/mocks/handlers/search.ts
  src/mocks/server.ts
  src/types/search.ts
Labels: 🚀 Feat

#49 [refactor] 메인페이지 서버 컴포넌트와 클라이언트 컴포넌트 분리 완료
  next.config.mjs
  src/api/chart.ts
  src/api/uploadmymusic 2.ts
  src/app/components/AlbumCover/AlbumCoverSystem.tsx
  src/app/components/AlbumCover/AlbumCoverUser.tsx
  src/app/main/genreMusicComponent.tsx
  src/app/main/otherPeoplePlayListComponent.tsx
  src/app/main/page.tsx
  src/app/main/popularMusicComponent.tsx
  src/app/main/popularTagComponent.tsx
  src/app/main/systemPlaylistComponent.tsx
  src/app/styles/theme.ts
  src/mocks/handlers/chartHandlers.ts
  src/mocks/server.ts
  src/types/albumCover.ts
  src/types/chart.ts
  src/types/genre.ts
Labels: 🧹 Refactor

#52 [feat] 나의 플레이리스트 썸네일 조회 API 연동 및 기능 구현 완료
  package.json
  src/api/chart.ts
  src/api/playlist.ts
  src/api/uploadmymusic 2.ts
  src/app/layout.tsx
  src/app/main/otherPeoplePlayListComponent.tsx
  src/app/main/page.tsx
  src/app/main/popularMusicComponent.tsx
  src/app/playlist/myPlaylistComponent.tsx
  src/app/playlist/page.tsx
  src/app/styles/SlideStyles.ts
  src/app/styles/globals.css
  src/mocks/browser.ts
  src/mocks/handlers/playlistHandlers.ts
  src/mocks/server.ts
  yarn.lock
Labels: 🚀 Feat

#53 [fe/#24] 재생목록 선택 기능구현
  src/api/playlist.ts
  src/app/main/page.tsx
  src/app/musicpage/page.tsx
  src/app/search/[keyward]/page.tsx
  src/mocks/browser.ts
  src/mocks/handlers/playlistHandlers.ts
  src/mocks/handlers/searchHandlers.ts
  src/mocks/server.ts
Labels: 🚀 Feat

#55 [feat] 팔로우한 플레이리스트 썸네일 조회 API 연동 및 기능 구현 완료
  src/api/playlist.ts
  src/app/components/Musicbar/Musicbar.tsx
  src/app/components/NavBar/NavigationBar.tsx
  src/app/playlist/followPlaylistComponent.tsx
  src/app/playlist/myPlaylistComponent.tsx
  src/app/playlist/page.tsx
  src/app/playlist/systemPlaylistComponent.tsx
  src/mocks/browser.ts
  src/mocks/handlers/playlistHandlers.ts
  src/mocks/server.ts
Labels: 🚀 Feat

#57 [fe/#28] 최근 감상한 곡 기능구현
  src/api/playlist.ts
  src/app/mypage/page.tsx
  src/mocks/browser.ts
  src/mocks/handlers/playlistHandlers.ts
  src/mocks/server.ts
Labels: 🚀 Feat

#61 [docs] env 설정
  src/api/playlist.ts
Labels: 📑 Docs

#64 [feat] 인기 태그 플레이리스트 썸네일 조회 API 연동 및 기능 구현 완료
  .gitignore
  src/api/playlist.ts
  src/app/components/AlbumCover/AlbumCoverSystem.tsx
  src/app/components/Musicbar/Musicbar.tsx
  src/app/components/NavBar/NavigationBar.tsx
  src/app/layout.tsx
  src/app/main/chartMusicComponent.tsx
  src/app/main/page.tsx
  src/app/main/popularTagComponent.tsx
  src/mocks/browser.ts
  src/mocks/handlers/playlistHandlers.ts
  src/mocks/server.ts
  src/types/ignorePath.ts
Labels: 🚀 Feat

#66 [feat] 장르 플레이리스트 썸네일 조회 API 연동 및 기능 구현 완료
  src/api/playlist.ts
  src/app/main/GenreColorList.css
  src/app/main/genreMusicComponent.tsx
Labels: 🚀 Feat

#68 [feat] 다른 유저가 선택한 플레이리스트 썸네일 조회 API 연동 및 기능 구현 완료
  src/api/playlist.ts
  src/app/components/AlbumCover/AlbumCoverUser.tsx
  src/app/main/allPlayListComponent.tsx
  src/app/main/genreMusicComponent.tsx
  src/app/main/page.tsx
Labels: 🚀 Feat

#70 [feat] 시스템 플레이리스트 썸네일 조회 API 연동 및 기능 구현 완료
  src/api/playlist.ts
  src/app/components/AlbumCover/AlbumCoverSystem.tsx
  src/app/main/systemPlaylistComponent.tsx
Labels: 🚀 Feat

#71 [feat] 카카오 소셜 로그인 기능 구현 완료
  package.json
  src/api/genre.ts
  src/api/login.ts
  src/api/uploadmymusic.ts
  src/app/AxiosC.tsx
  src/app/Cookies.tsx
  src/app/GenrePage/page.tsx
  src/app/LogInPage/page.tsx
  src/app/MymusicAI/page.tsx
  src/app/auth/_app.tsx
  src/app/auth/nextauth.ts
  src/app/page.tsx
  yarn.lock
Labels: 🚀 Feat

#73 [fe/#32] 뮤직바 - 음악상세페이지 동기화
  src/api/music.ts
  src/app/AxiosC.tsx
  src/app/components/Musicbar/Musicbar.tsx
  src/app/components/NavBar/NavigationBar.tsx
  src/app/components/audio/Audio.tsx
  src/app/genre_select/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/musicpage/[trackId]/page.tsx
  src/app/musicpage/page.tsx
  src/app/page.tsx
  src/app/styles/globals.css
  src/types/ignorePath.ts
Labels: 🚀 Feat

#78 [file] : 폴더명 수정
  src/app/GenrePage/page.tsx
  src/app/LogInPage/page.tsx
  src/app/music_post/page.tsx
Labels: 📑 Docs

#80 [fix] 슬라이더 버그 수정
  src/app/auth/_app.tsx
  src/app/auth/nextauth.ts
  src/app/components/Musicbar/Musicbar.tsx
  src/app/musicpage/[trackId]/page.tsx
Labels: 🏷 Fix

#82 [design] 스크롤 바 디자인 적용
  src/app/components/Musicbar/Musicbar.tsx
  src/app/musicpage/page.tsx
  src/app/styles/globals.css
  src/app/track/[trackId]/page.tsx
Labels: 🎨 Design

#84 [chore] tailwindcss prettier 적용
  .prettierrc
  package.json
  src/app/components/Musicbar/Musicbar.tsx
  src/app/track/[trackId]/page.tsx
  yarn.lock
Labels: 🧭 Chore
