Repository DreamVault-2024/dreamvalut-frontend, pull requests merged in 2024-03, with the labels that each got.

#8 [UI/Design] 공용 컴포넌트 - 앨범 커버(시스템 생성) 퍼블리싱 완료
  src/app/components/AlbumCover/AlbumCoverSystem.tsx
  src/app/components/AlbumCover/AlbumCoverUser.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
Labels: 🎨 Design

#9 [UI/Design] 공용 컴포넌트 - 내비게이션바 퍼블리싱
  src/app/components/NavigationBar.tsx
  src/app/index.css
  src/app/layout.tsx
  src/app/page.tsx
  src/app/styles/NavBar.css
  tsconfig.json
Labels: 🎨 Design

#11 [UI/Design] 공용 컴포넌트 - 재생바 퍼블리싱
  .gitmessage.txt
  package.json
  public/play-btn/play30.png
  public/play-btn/play60.png
  public/play-btn/play90.png
  public/pre-skip-btn/pre-skip-btn30.png
  public/pre-skip-btn/pre-skip-btn60.png
  public/pre-skip-btn/pre-skip-btn90.png
  public/replay-btn/replay-btn30.png
  public/replay-btn/replay-btn60.png
  public/replay-btn/replay-btn90.png
  public/skip-btn/skip-btn30.png
  public/skip-btn/skip-btn60.png
  public/skip-btn/skip-btn90.png
  src/app/components/Musicbar/Musicbar.tsx
  src/app/components/NavigationBar.tsx
  src/app/page.tsx
  tsconfig.json
  yarn.lock
Labels: 🎨 Design, 🏷 Fix

#13 [UI/Design] 음악 상세페이지 퍼블리싱
  public/next.svg
  public/play-btn/play30.png
  public/play-btn/play60.png
  public/play-btn/play90.png
  public/pre-skip-btn/pre-skip-btn30.png
  public/pre-skip-btn/pre-skip-btn60.png
  public/pre-skip-btn/pre-skip-btn90.png
  public/replay-btn/replay-btn30.png
  public/replay-btn/replay-btn60.png
  public/replay-btn/replay-btn90.png
  public/skip-btn/skip-btn30.png
  public/skip-btn/skip-btn60.png
  public/skip-btn/skip-btn90.png
  public/vercel.svg
  src/app/components/Musicbar/Musicbar.tsx
  src/app/components/NavigationBar.tsx
  src/app/musicpage/page.tsx
Labels: 🎨 Design

#15 [UI/Design] 로그인 페이지 퍼블리싱 완료, 내비게이션 바 수정 완료
  src/app/LogInPage/page.tsx
  src/app/components/NavBar/NavigationBar.tsx
  src/app/components/NavigationBar.tsx
  src/app/globals.css
  src/app/index.css
  src/app/musicpage/page.tsx
  src/app/page.tsx
  src/app/styles/NavBar.css
Labels: 🎨 Design

#18 [UI/Design] 마이페이지 퍼블리싱
  src/app/components/Musicbar/Musicbar.tsx
  src/app/components/NavBar/NavigationBar.tsx
  src/app/mypage/page.tsx
Labels: 🎨 Design

#19 [UI/Design] 장르 페이지 퍼블리싱 완료
  src/app/GenrePage/page.tsx
  src/app/components/NavBar/NavigationBar.tsx
  src/app/globals.css
  src/app/page.tsx
Labels: 🎨 Design

#21 [UI/Design] 메인 페이지 퍼블리싱
  src/app/components/AlbumCover/AlbumCoverSystem.tsx
  src/app/components/AlbumCover/AlbumCoverUser.tsx
  src/app/components/Musicbar/Musicbar.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/main/GenreColorList.css
  src/app/main/page.tsx
  src/app/page.tsx
Labels: 🎨 Design

#24 [UI/Design] 플레이리스트 페이지 퍼블리싱 완료
  src/app/GenrePage/page.tsx
  src/app/components/Musicbar/Musicbar.tsx
  src/app/components/NavBar/NavigationBar.tsx
  src/app/favicon.ico
  src/app/globals.css
  src/app/layout.tsx
  src/app/main/page.tsx
  src/app/playlist/page.tsx
Labels: 🎨 Design

#26 [UI/Design] 검색 결과페이지 퍼블리싱
  src/app/components/NavBar/NavigationBar.tsx
  src/app/search/page.tsx
Labels: 🎨 Design

#29 [UI/Design] 음악 상세페이지 배경 디자인 수정
  src/app/musicpage/page.tsx
Labels: 🎨 Design

#31 [UI/Design] 나만의 음악 등록 페이지 수정
  src/app/MymusicAI/page.tsx
Labels: 🎨 Design

#32 [UI/Design] 플레이리스트 상세페이지 퍼블리싱 완료
  package.json
  src/app/layout.tsx
  src/app/playlist/[playlistTitle]/page.tsx
  src/app/playlist/page.tsx
  yarn.lock
Labels: 🎨 Design

#36 [chore] MSW 세팅
  package.json
  public/mockServiceWorker.js
  src/app/components/NavBar/NavigationBar.tsx
  src/app/layout.tsx
  src/app/mocks/MSWComponent.tsx
  src/app/mocks/browser.ts
  src/app/mocks/handlers.ts
  src/app/mocks/index.ts
  src/app/mocks/server.ts
  src/app/page.tsx
  yarn.lock
Labels: 🧭 Chore
