Repository DreamVault-2024/dreamvalut-frontend, pull requests merged in 2024-05, with the labels that each got.

#88 [feat] 나만의 음악 등록 폼 제출 기능 구현
  src/api/genre.ts
  src/api/uploadmymusic.ts
  src/app/components/NavBar/NavigationBar.tsx
  src/app/post_music/page.tsx
Labels: 🚀 Feat

#90 나만의 음악 등록 폼 - 주석 삭제
  src/api/uploadmymusic.ts
  src/app/post_music/page.tsx
Labels: 🧹 Refactor

#91 [feat] 음악상세 - 좋아요 기능 구현
  src/api/login.ts
  src/api/music.ts
  src/app/components/Musicbar/Musicbar.tsx
  src/app/login/page.tsx
  src/app/track/[trackId]/page.tsx
Labels: 🚀 Feat

#95 [feat] 토큰 기능 구현
  src/api/axios_interceptor.ts
  src/api/login.ts
  src/app/genre_select/page.tsx
  src/app/login/page.tsx
  src/app/post_music/page.tsx
Labels: 🚀 Feat

#97 [feat]실제 API로 변경
  src/api/genre.ts
  src/api/login.ts
  src/api/uploadmymusic.ts
  src/app/genre_select/page.tsx
  src/app/login/page.tsx
Labels: 🚀 Feat

#99 [feat] Mock Api -> Test Server Api 변경
  package.json
  src/api/chart.ts
  src/api/music.ts
  src/api/playlist.ts
  src/app/components/AlbumCover/AlbumCoverSystem.tsx
  src/app/components/AlbumCover/AlbumCoverUser.tsx
  src/app/main/AllPlayList.tsx
  src/app/main/Chart.tsx
  src/app/main/Genre.tsx
  src/app/main/GenreColorArr.css
  src/app/main/SystemPlaylist.tsx
  src/app/main/Tag.tsx
  src/app/main/page.tsx
  src/app/main/popularMusicComponent.tsx
  src/app/main/popularTagComponent.tsx
  src/app/playlist/FollowPlaylist.tsx
  src/app/playlist/FollowSystemPlaylist.tsx
  src/app/playlist/MyPlaylist.tsx
  src/app/playlist/[playlistId]/MusicElement.tsx
  src/app/playlist/[playlistId]/PlayButton.tsx
  src/app/playlist/[playlistId]/page.tsx
  src/app/playlist/[playlistTitle]/page.tsx
  src/app/playlist/page.tsx
  src/app/styles/slide.ts
  src/mocks/browser.ts
  src/mocks/handlers/likeHandler.ts
  src/mocks/server.ts
  src/types/albumCover.ts
  src/types/playlist.ts
Labels: 🚀 Feat

#101 [build] Github Actions를 이용한 S3+CloudFront 배포 자동화 #51
  .github/workflows/deploy.yml
Labels: ⛑️  Build

#102 [feat/#47] 검색기능 구현
  src/api/login.ts
  src/app/components/FavoriteButton.tsx
  src/app/login/page.tsx
  src/app/post_music/page.tsx
  src/app/search/[keyward]/page.tsx
  src/types/search.ts
Labels: 🚀 Feat

#105 [feat] NextJS 배포 시 생기는 에러 해결 및 기타 디자인 수정
  package.json
  src/api/axios_interceptor.ts
  src/api/genre.ts
  src/api/login.ts
  src/api/music.ts
  src/api/uploadmymusic.ts
  src/app/Cookies.tsx
  src/app/components/FavoriteButton.tsx
  src/app/components/Musicbar/Musicbar.tsx
  src/app/components/audio/Audio.tsx
  src/app/genre_select/page.tsx
  src/app/layout.tsx
  src/app/playlist/FollowSystemPlaylist.tsx
  src/app/playlist/[playlistId]/page.tsx
  src/app/post_music/page.tsx
  src/app/track/[trackId]/page.tsx
  yarn.lock
Labels: 🧹 Refactor, 🚀 Feat, 🎨 Design

#110 [build] Github Actions를 통한 ECS 배포 자동화 구현 #54
  .github/workflows/deploy.yml
  next.config.mjs
  prod.Dockerfile
  src/app/api/health/route.ts
Labels: ⛑️  Build

#112 AWS CodeDeploy 배포 구성을 위한 `appspec.yml` 파일 추가 #55
  appspec.yml
Labels: ⛑️  Build, 🚀 Feat

#114 [comment] `deploy.yml` 주석 설명 추가 #56
  .github/workflows/deploy.yml
Labels: 🧹 Refactor

#116 [comment] `deploy.yml` 주석 설명 추가(다운 설명용) #57
  .github/workflows/deploy.yml
Labels: 🧹 Refactor

#119 [feat/#52] 무한스크롤 컴포넌트 추상화 및 적용
  .eslintrc.json
  src/api/music.ts
  src/app/components/InfiniteScroll.tsx
  src/app/genre/[genreId]/page.tsx
  src/app/playlist/FollowSystemPlaylist.tsx
  src/app/playlist/[playlistId]/page.tsx
  src/app/search/[keyward]/page.tsx
  src/app/styles/globals.css
  src/app/tag/[tagId]/page.tsx
  src/types/music.ts
  src/types/playlist.ts
Labels: 🚀 Feat

#120 [feat] 메인 페이지 인기 차트 기능 재구현
  src/api/chart.ts
  src/app/components/InfiniteScroll.tsx
  src/app/genre/[genreId]/MusicElement.tsx
  src/app/home/AllPlayList.tsx
  src/app/home/Chart.tsx
  src/app/home/Genre.tsx
  src/app/home/GenreColorArr.css
  src/app/home/SystemPlaylist.tsx
  src/app/home/Tag.tsx
  src/app/home/page.tsx
  src/app/layout.tsx
  src/app/main/page.tsx
  src/app/playlist/[playlistId]/MusicElement.tsx
  src/app/tag/[tagId]/MusicElement.tsx
  src/app/track/[trackId]/page.tsx
  src/types/chart.ts
Labels: 🚀 Feat

#124 [feat/#60] 최근 감상한 곡, 이름 및 장르취향 수정 기능구현
  src/api/genre.ts
  src/api/playlist.ts
  src/api/user.ts
  src/app/mypage/page.tsx
Labels: 🚀 Feat

#127 [feat] 로그아웃 기능 구현 및 로그인 버튼 디자인 수정
  .eslintrc.json
  src/api/axios_interceptor.ts
  src/api/genre.ts
  src/api/uploadmymusic.ts
  src/app/components/NavBar/NavigationBar.tsx
  src/app/login/page.tsx
  src/app/post_music/page.tsx
  src/app/styles/globals.css
  src/util/login.ts
Labels: 🚀 Feat, 🎨 Design

#129 [design] 로그인 페이지 반응형 적용
  src/app/login/page.tsx
Labels: 🎨 Design

#131 [design] 장르 페이지 반응형 적용 및 버튼 디자인 수정
  src/app/genre_select/page.tsx
  src/app/styles/globals.css
Labels: 🎨 Design

#133 [design] 내비게이션 바 반응형 적용
  package.json
  src/app/components/NavBar/NavigationBar.tsx
  src/app/styles/globals.css
  yarn.lock
Labels: 🎨 Design

#134 [design] 메인 페이지 반응형&적응형 디자인 적용
  src/api/playlist.ts
  src/app/components/AlbumCover/AlbumCoverSystem.tsx
  src/app/components/AlbumCover/AlbumCoverUser.tsx
  src/app/components/NavBar/NavigationBar.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/main/AllPlayList.tsx
  src/app/main/Chart.tsx
  src/app/main/Genre.tsx
  src/app/main/GenreColorArr.css
  src/app/main/SystemPlaylist.tsx
  src/app/main/Tag.tsx
  src/app/main/page.tsx
  src/app/mypage/page.tsx
  src/app/playlist/page.tsx
  src/app/search/[keyward]/page.tsx
  src/app/styles/globals.css
  src/app/track/[trackId]/page.tsx
  src/types/genre.ts
  src/util/matchMedia.ts
Labels: 🎨 Design

#135 [fix] 음악 재생 버그수정
  src/api/music.ts
  src/app/components/Musicbar/Musicbar.tsx
  src/app/components/audio/Audio.tsx
  src/app/layout.tsx
  src/app/track/[trackId]/page.tsx
Labels: 🏷 Fix

#142 [feat] 음악페이지 반응형 디자인 적용
  src/app/track/[trackId]/page.tsx
Labels: 🎨 Design
