Repository DreamVault-2024/dreamvalut-frontend, pull requests merged in 2024-06, with the labels that each got.

#143 [design] 마이페이지 반응형 적용
  src/app/mypage/page.tsx
Labels: 🎨 Design

#145 [feat] 로그아웃 기능 구현
  package.json
  src/api/logout.ts
  src/app/components/NavBar/NavigationBar.tsx
  yarn.lock
Labels: 🚀 Feat

#146 [feat] 검색페이지 반응형 디자인 적용
  src/app/components/FavoriteButton.tsx
  src/app/components/NavBar/NavigationBar.tsx
  src/app/search/[keyward]/page.tsx
Labels: 🎨 Design

#147 [refactor] 상세 플레이리스트 라우팅 방식 수정
  src/api/playlist.ts
  src/app/components/AlbumCover/AlbumCoverSystem.tsx
  src/app/components/AlbumCover/AlbumCoverUser.tsx
  src/app/genre/[genreId]/MusicElement.tsx
  src/app/genre/[genreId]/page.tsx
  src/app/main/Chart.tsx
  src/app/main/Genre.tsx
  src/app/playlist/MyPlaylist.tsx
  src/app/playlist/[param]/MusicElement.tsx
  src/app/playlist/[param]/PlayButton.tsx
  src/app/playlist/[param]/page.tsx
  src/app/playlist/[playlistId]/PlayButton.tsx
  src/app/tag/[tagId]/MusicElement.tsx
  src/app/tag/[tagId]/PlayButton.tsx
  src/app/tag/[tagId]/page.tsx
  src/types/albumCover.ts
  src/types/genre.ts
  src/types/playlist.ts
Labels: 🧹 Refactor

#149 [design] 플레이리스트 페이지 적응형 디자인 적용
  src/app/auth/[loginType]/page.tsx
  src/app/components/AlbumCover/AlbumCoverSystem.tsx
  src/app/components/AlbumCover/AlbumCoverUser.tsx
  src/app/main/AllPlayList.tsx
  src/app/main/SystemPlaylist.tsx
  src/app/main/Tag.tsx
  src/app/playlist/FollowPlaylist.tsx
  src/app/playlist/FollowSystemPlaylist.tsx
  src/app/playlist/MyPlaylist.tsx
  src/app/playlist/[param]/MusicElement.tsx
  src/app/playlist/[param]/PlayButton.tsx
  src/app/playlist/[param]/page.tsx
  src/app/playlist/page.tsx
Labels: 🎨 Design

#152 [design] 음악 등록페이지 디자인 수정 및 반응형 디자인 적용
  src/app/post_music/page.tsx
Labels: 🎨 Design

#154 [feat] 토큰 재발급 기능 구현
  next.config.mjs
  src/api/axios_interceptor.ts
  src/api/chart.ts
  src/api/genre.ts
  src/api/logout.ts
  src/api/music.ts
  src/api/playlist.ts
  src/api/uploadmymusic.ts
  src/api/user.ts
  src/app/AxiosC.tsx
  src/app/Cookies.tsx
  src/app/components/NavBar/NavigationBar.tsx
  src/app/post_music/page.tsx
Labels: 🚀 Feat, 🏷 Fix

#156 [design] 최근 감상한 곡리스트 디자인 수정
  src/app/mypage/page.tsx
Labels: 🎨 Design
